version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE
        - SQL_USER
        - SQL_PASSWORD
        - SQL_ROOT_PASSWORD
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql/
    # restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:42
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE
        - SQL_USER
        - SQL_ROOT_PASSWORD
        - SQL_HOSTNAME
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx:42
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME
        - NGINX_CERT_PATH
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind

networks:
  inception:
    name: inception
    driver: bridge