version: "3.8"

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/${LOGIN}/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

services:
# Mandatory services
  nginx:
    image: nginx:42
    container_name: nginx
    init: true
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME
        - NGINX_CERT_PATH
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

  mariadb:
    image: mariadb:42
    container_name: mariadb
    init: true
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - WP_DB_NAME
        - WP_DB_USER
        - WP_DB_PASSWORD
    expose:
      - 3306
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:42
    container_name: wordpress
    init: true
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME
      - WP_DB_NAME
      - WP_DB_USER
      - WP_DB_PASSWORD
      - WP_DB_EMAIL
      - WP_GUEST_USER
      - WP_GUEST_PASSWORD
      - WP_GUEST_EMAIL
    expose:
      - 9000
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: always

# Bonus services
  adminer:
    container_name: adminer
    image: adminer:42
    init: true
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress
      
  cadvisor:
    container_name: cadvisor
    image: cadvisor:42
    init: true
    build:
      context: requirements/bonus/cadvisor
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    devices:
      - dev/kmsg
    restart: always
    depends_on:
      - wordpress

  redis:
    container_name: redis
    image: redis:42
    init: true
    build:
      context: requirements/bonus/redis-cache
      dockerfile: Dockerfile
    privileged: true
    networks:
      - inception
    ports:
      - 6379
    restart: always

  static:
    container_name: static
    image: static:42
    init: true
    build:
      context: requirements/bonus/static-website
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 3000
    restart: always

  ftp:
    container_name: ftp
    image: ftp:42
    init: true
    build:
      context: requirements/bonus/ftp-server
      dockerfile: Dockerfile
    environment:
      - FTP_USER
      - FTP_PASSWORD
    networks:
      - inception
    ports:
      - 20:20
      - 21:21
      - 21000-21010:21000-21010
    volumes:
      - wordpress:/home/${FTP_USER}/ftp
    restart: always
    depends_on:
      - wordpress